### PR TITLE
Update README to reflect unmaintained status

### PR DESCRIPTION
**Pull request by bkeepers**
@leereilly, @cameronmcefee: it looks like this repository is no longer being maintained. I'd like to propose that we make it even more explicit in the `README.md` and transfer the repository to @github-archive. Let me know if you have any reservations about that.

### CODE REVIEW

**Comment by leereilly** [comment]
These are the old logos and this repository's not getting much traffic, so I'm in favor :+1:

**Minor concern:** The (ever-popular) _Fork Me on GitHub_ ribbon PSD files are stored in this repository. The code samples and ribbons themselves are still accessible via the [original blog post](https://github.com/blog/273-github-ribbons), but the PSD files are still referenced there. We should delete / ~~strikethrough~~ that in the blog post when this ships.

**Comment by bkeepers** [comment]
Hmm, [looking at the traffic graphs](https://github.com/github/media/graphs/traffic), the ribbons aren't even the most popular thing in this repository.

We still haven't updated the ribbons in ~6 years. Do we ever have plans to? If we want to keep it around, maybe we should remove the outdated assets and only have the ribbons? It's up to you.

**Comment by bkeepers** [comment]
@leereilly what do you think?

**Comment by leereilly** [comment]
I'm fine with updating the `README.md` and moving the repository, plus I'm confident @cameronmcefee _won't_ ask us to undo these changes when he returns from :baby: leave :+1:

**Comment by cameronmcefee** [comment]
:+1:

**Pull request merged**
